### ISSUE TITLE
Missing quaternion.py when Constructing Music-to-Dance Benchmark

### ISSUE THREAD

**Issue by hoyeYang** [cure-lab/MotionCraft#4]
Great work!
After installing required packages. I met the following problem when constructing the Music-to-Dance Benchmark.
```bash
Traceback (most recent call last):
  File "/mnt/Projects/MotionCraft/data/datasets/finedance/pre_motion.py", line 12, in <module>
    from quaternion import ax_to_6v, ax_from_6v
ModuleNotFoundError: No module named 'quaternion‘
```

**Comment by yxbian23** [comment]
> Great work! After installing required packages. I met the following problem when constructing the Music-to-Dance Benchmark.
> 
> ```shell
> Traceback (most recent call last):
>   File "/mnt/Projects/MotionCraft/data/datasets/finedance/pre_motion.py", line 12, in <module>
>     from quaternion import ax_to_6v, ax_from_6v
> ModuleNotFoundError: No module named 'quaternion‘
> ```

Sorry about the missing file! I will be adding the relevant documents in the coming weeks, or you can directly use the Pytorch3D API, as this part is equivalent to the implementation in the Pytorch3D API.

**Comment by yxbian23** [comment]
The relevant missing functions have all been updated. Thank you for your question, and feel free to ask me further questions!
